name: script_tests
description: Execute all script tests, including those with external dependencies, if merging to master
inputs:
  commitish:  # id of input
    description: 'MRtrix3 git commitish to check out for testing'
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.commitish }}

